mod workspace;
mod sidebar;
mod commit_panel;
mod status_bar;
mod title_bar;
mod toolbar;
mod detail_panel;
mod command_palette;
mod interactive_rebase;
mod settings_modal;
mod branch_dialog;
mod confirm_dialog;
mod repo_opener;
mod shortcuts_help;
pub(crate) mod avatar_resolver;

pub use workspace::*;
pub use sidebar::*;
pub use commit_panel::*;
pub use status_bar::*;
pub use title_bar::*;
pub use toolbar::*;
pub use detail_panel::*;
pub use command_palette::*;
pub use interactive_rebase::*;
pub use settings_modal::*;
pub use branch_dialog::*;
pub use confirm_dialog::*;
pub use repo_opener::*;
pub use shortcuts_help::*;
