//! The command registry: one `commands!` declaration that defines every
//! rgitui command, its gpui action and its default key binding.
//!
//! # Key contexts
//!
//! `Workspace` is set on the workspace root element. The root adds `modal`
//! whenever an overlay or dialog is open, so `Workspace && !modal` is the
//! scope for shortcuts that must not fire while a modal is up.
//! `TextInput` is set by [`rgitui_ui::TextInput`], so `!TextInput` keeps
//! unmodified single-key shortcuts from stealing typed characters.
//!
//! Every panel, picker and dialog that owns a row selection also sets `List`
//! alongside its own name, e.g. `key_context("BlameView List")`. The shared
//! `menu` commands below are bound once against `List`, and each view registers
//! its own handler for them; gpui dispatches an action from the focused element
//! outwards and the first handler consumes it, so the view that owns the
//! selection is the one that moves. The same mechanism resolves `menu::Cancel`
//! and `menu::Confirm` — there is no cascade of `if visible` checks anywhere.
//!
//! # Views in other crates
//!
//! `GraphView` (`rgitui_graph`) and `DiffViewer` (`rgitui_diff`) sit *below*
//! this crate in the dependency graph, so they cannot name these actions. Their
//! commands are therefore declared here in the `graph` and `diff` namespaces and
//! handled on the workspace root, which is an ancestor of both on every dispatch
//! path; the views themselves only declare their key context. That also means
//! they do not join the `List` group: a shared `menu` command has to be handled
//! by the element that owns the selection, and these two cannot handle anything.

// The `if <predicate>` clause of `commands!` resolves these by name at the
// invocation site; `always_show` is the default and is referenced through
// `$crate`, so it is not imported here.
use crate::command_palette::{
    has_changes, has_github_token, has_multi_commit_selection, has_remotes, has_staged,
    has_stashes, in_progress_operation, is_bisecting, worktree_clean, CommandContext,
};

/// Static description of a single command.
///
/// Generated by `commands!`; see [`ALL_COMMANDS`].
pub struct CommandMeta {
    /// The command this metadata describes.
    pub id: CommandId,
    /// The view whose `commands!` block declared it. Groups the generated docs.
    pub view: &'static str,
    /// The gpui action namespace.
    pub namespace: &'static str,
    /// The full gpui action name, as written in `keymap.json`.
    pub action_name: &'static str,
    /// Default bindings as `(keystrokes, key context)`. Empty when the command
    /// has no default binding. One command may bind several keystrokes, each in
    /// its own context — that is how `down` stays live inside a text field while
    /// the vim-style `j` for the same command stands down.
    pub default_bindings: &'static [(&'static str, &'static str)],
    /// Doc comment from the declaration. Leading whitespace is not trimmed.
    pub description: &'static str,
    /// Whether the command is offered in the command palette.
    pub in_palette: bool,
    /// Command-palette availability predicate.
    pub availability: fn(CommandContext) -> bool,
}

impl CommandMeta {
    /// The description with doc-comment padding removed.
    pub fn description(&self) -> &'static str {
        self.description.trim()
    }
}

commands! {
    view Workspace in rgitui context "Workspace && !modal" {
        /// Download objects and refs from the tracked remote.
        Fetch "secondary-shift-r" if has_remotes;
        /// Fetch from and integrate with the tracked remote branch.
        Pull unbound if has_remotes;
        /// Update the remote ref along with associated objects.
        Push unbound if has_remotes;
        /// Push every open repository.
        PushAll unbound if has_remotes;
        /// Pull every open repository.
        PullAll unbound if has_remotes;
        /// Overwrite the remote branch with the local one.
        ForcePush unbound if has_remotes;
        /// Commit the staged changes using the message in the commit panel.
        Commit "secondary-enter" if has_staged;
        /// Stage every change in the working tree.
        StageAll "secondary-s" if has_changes;
        /// Unstage everything currently staged.
        UnstageAll ["secondary-shift-s", "secondary-u"] if has_changes;
        /// Stash the working tree and index.
        StashSave "secondary-z" if has_changes;
        /// Apply the latest stash entry and drop it.
        StashPop "secondary-shift-z" if has_stashes;
        /// Apply the latest stash entry and keep it.
        StashApply unbound if has_stashes;
        /// Delete a stash entry.
        StashDrop unbound if has_stashes;
        /// Create a new branch.
        CreateBranch "secondary-b";
        /// Delete a branch.
        DeleteBranch unbound;
        /// Rename a branch.
        RenameBranch unbound;
        /// Merge another branch into the current one.
        MergeBranch unbound if worktree_clean;
        /// Create a tag.
        CreateTag unbound;
        /// Create a linked worktree.
        CreateWorktree unbound;
        /// Open a pull request for the current branch.
        CreatePr unbound if has_github_token;
        /// Cherry-pick a commit onto the current branch.
        CherryPick unbound if worktree_clean;
        /// Revert a commit.
        RevertCommit unbound if worktree_clean;
        /// Start an interactive rebase.
        InteractiveRebase unbound if worktree_clean;
        /// Discard every uncommitted change.
        DiscardAll unbound if has_changes;
        /// Delete untracked files.
        CleanUntracked unbound;
        /// Reset the working tree and index to HEAD.
        ResetHard unbound if has_changes;
        /// Abort the merge, rebase, cherry-pick or revert in progress.
        AbortOperation unbound if in_progress_operation;
        /// Continue the merge, rebase, cherry-pick or revert in progress.
        ContinueMerge unbound if in_progress_operation;
        /// Switch the diff viewer between unified and side-by-side.
        ToggleDiffMode "shift-d" in "Workspace && !modal && !TextInput";
        /// Search the commit graph.
        Search ["secondary-f", "/" in "Workspace && !modal && !TextInput"];
        /// Generate a commit message with the configured AI provider.
        AiMessage "secondary-g" if has_staged;
        /// Reload the repository state from disk.
        Refresh "f5";
        /// Open the settings window.
        Settings "secondary-," in "Workspace";
        /// Open the repository picker.
        OpenRepo "secondary-o" in "Workspace";
        // Control rather than the primary modifier: macOS reserves Cmd+H for
        // Hide Application, so a `secondary-` binding would never fire there.
        /// Close every tab and return to the workspace home screen.
        WorkspaceHome "ctrl-h";
        /// Reopen the most recently saved workspace.
        RestoreLastWorkspace unbound;
        /// Show the keyboard shortcut reference.
        Shortcuts "?" in "Workspace && !TextInput";
        /// Focus the sidebar to switch branches.
        SwitchBranch "secondary-shift-b";
        /// Blame the selected file.
        Blame unbound;
        /// Undo the last git operation.
        Undo unbound;
        /// Show the commit history of the selected file.
        FileHistory unbound;
        /// Show the reflog.
        Reflog unbound;
        /// Show the submodule list.
        Submodules unbound;
        /// Show the bisect log.
        Bisect unbound if is_bisecting;
        /// Start a bisect session.
        BisectStart unbound if worktree_clean;
        /// Mark the current bisect commit as good.
        BisectGood unbound if is_bisecting;
        /// Mark the current bisect commit as bad.
        BisectBad unbound if is_bisecting;
        /// End the bisect session and restore HEAD.
        BisectReset unbound if is_bisecting;
        /// Skip the current bisect commit.
        BisectSkip unbound if is_bisecting;
        /// Search the contents of the working tree.
        GlobalSearch "secondary-shift-f";
        /// Toggle the issues panel.
        ToggleIssues "alt-5";
        /// Toggle the pull requests panel.
        TogglePullRequests "alt-6";
        /// Toggle the branch health panel.
        ToggleBranchHealth "alt-7";
        /// Toggle the stashes panel.
        ToggleStashes "alt-8";
        /// Create a branch from a stash entry.
        StashBranch unbound if has_stashes;
        /// Open the theme editor.
        OpenThemeEditor ["secondary-shift-t", "alt-9"] in "Workspace";
        /// Toggle the command palette.
        CommandPalette "secondary-shift-p" in "Workspace" [hidden];
        // Control rather than the primary modifier: macOS reserves Cmd+Tab for
        // the application switcher, and the WindowServer swallows it before the
        // app sees it. Ctrl+Tab is also the native chord there.
        /// Activate the next repository tab.
        NextTab "ctrl-tab" [hidden];
        /// Activate the previous repository tab.
        PrevTab "ctrl-shift-tab" [hidden];
        /// Close the active repository tab.
        CloseTab "secondary-w" [hidden];
        /// Move keyboard focus to the sidebar.
        FocusSidebar "alt-1" [hidden];
        /// Move keyboard focus to the commit graph.
        FocusGraph "alt-2" [hidden];
        /// Move keyboard focus to the commit detail panel.
        FocusDetailPanel "alt-3" [hidden];
        /// Move keyboard focus to the diff viewer.
        FocusDiffViewer "alt-4" [hidden];
        /// Move keyboard focus to the next panel.
        FocusNextPanel "tab" in "Workspace && !modal && !TextInput" [hidden];
        /// Move keyboard focus to the previous panel.
        FocusPrevPanel "shift-tab" in "Workspace && !modal && !TextInput" [hidden];
        /// Narrow the detail panel.
        ShrinkDetailPanel "secondary-[" [hidden];
        /// Widen the detail panel.
        GrowDetailPanel "secondary-]" [hidden];
        /// Shorten the diff viewer.
        ShrinkDiffViewer "secondary-up" [hidden];
        /// Heighten the diff viewer.
        GrowDiffViewer "secondary-down" [hidden];
        /// Open keymap.json in your editor to rebind shortcuts.
        OpenKeymap unbound;
    }

    // Bound once and handled by whichever element owns the selection or the
    // dismissal. See the module docs for how gpui resolves that.
    view Menu in menu context "List" {
        /// Dismiss the focused overlay, dialog, search or selection.
        Cancel "escape" in "Workspace || SettingsWindow" [hidden];
        /// Activate the selected row, or submit the focused dialog.
        Confirm ["enter" in "Workspace || SettingsWindow", "space" in "List && !TextInput"]
            [hidden];
        /// Move the selection down one row.
        SelectNext ["down", "j" in "List && !TextInput"] [hidden];
        /// Move the selection up one row.
        SelectPrev ["up", "k" in "List && !TextInput"] [hidden];
        /// Move the selection to the first row.
        SelectFirst ["home", "g" in "List && !TextInput"] [hidden];
        /// Move the selection to the last row.
        SelectLast ["end", "shift-g" in "List && !TextInput"] [hidden];
    }

    view GraphView in graph context "GraphView && !modal && !TextInput" {
        /// Select the next commit in the graph.
        GraphSelectNext ["down" in "GraphView && !modal", "j"] [hidden];
        /// Select the previous commit in the graph.
        GraphSelectPrev ["up" in "GraphView && !modal", "k"] [hidden];
        /// Select the newest commit in the graph.
        GraphSelectFirst ["home" in "GraphView && !modal", "g"] [hidden];
        /// Select the oldest loaded commit in the graph.
        GraphSelectLast ["end" in "GraphView && !modal", "shift-g"] [hidden];
        /// Add the next commit in the graph to the selection.
        GraphExtendSelectionNext ["shift-down", "shift-j"] [hidden];
        /// Add the previous commit in the graph to the selection.
        GraphExtendSelectionPrev ["shift-up", "shift-k"] [hidden];
        // Bare `s`, matching the rebase editor below where `s` already means
        // squash. `secondary-shift-s` would be dispatched ahead of the
        // workspace's `rgitui::UnstageAll`, taking that keystroke away from it
        // whenever the graph held focus.
        /// Squash the selected commits into the oldest of them.
        SquashSelected "s" if has_multi_commit_selection [hidden];
        /// Close the graph search, or dismiss the graph context menu.
        GraphCancel "escape" in "GraphView && !modal" [hidden];
        /// Copy the selected commit's SHA to the clipboard.
        CopyCommitSha "y" [hidden];
        /// Copy the selected commit's message to the clipboard.
        CopyCommitMessage "shift-c" [hidden];
    }

    // The diff viewer hosts no text field, but the bare letters below still carry
    // `!TextInput` so that `bare_character_bindings_stand_down_for_text_input`
    // holds for every binding in the registry without exceptions.
    view DiffViewer in diff context "DiffViewer && !modal && !TextInput" {
        /// Move the diff cursor down one row.
        DiffSelectNext ["down", "j"] [hidden];
        /// Move the diff cursor up one row.
        DiffSelectPrev ["up", "k"] [hidden];
        /// Move the diff cursor to the first row.
        DiffSelectFirst ["home", "g"] [hidden];
        /// Move the diff cursor to the last row.
        DiffSelectLast ["end", "shift-g"] [hidden];
        /// Jump to the next hunk.
        NextHunk "]" [hidden];
        /// Jump to the previous hunk.
        PrevHunk "[" [hidden];
        /// Cycle the diff viewer's display mode.
        ToggleDiffDisplayMode "d" [hidden];
        /// Toggle line-level selection in the diff viewer.
        TogglePartialSelection "p" [hidden];
        /// Stage the hunks or lines under the diff selection.
        StageSelection ["s", "shift-s"] [hidden];
        /// Unstage the hunks or lines under the diff selection.
        UnstageSelection ["u", "shift-u"] [hidden];
        /// Stage the hunk under the diff cursor.
        StageCurrentHunk "alt-s" [hidden];
        /// Unstage the hunk under the diff cursor.
        UnstageCurrentHunk "alt-u" [hidden];
        /// Copy the selected diff lines to the clipboard.
        CopyDiffSelection "secondary-c" [hidden];
        /// Select every line in the diff.
        SelectAllDiffLines "secondary-a" [hidden];
    }

    view DetailPanel in detail context "DetailPanel && !modal && !TextInput" {
        /// Switch the changed-files list between the flat and tree layouts.
        ToggleFileTree "v" [hidden];
        /// Show the previous commit's details.
        PrevCommitDetails "[" [hidden];
        /// Show the next commit's details.
        NextCommitDetails "]" [hidden];
        /// Filter the changed-files list.
        FileSearch ["/", "secondary-f" in "DetailPanel && !modal"] [hidden];
    }

    view Sidebar in sidebar context "Sidebar && !modal && !TextInput" {
        /// Stage or unstage the selected file.
        ToggleStageRow "s" [hidden];
        /// Discard the selected change, or delete the selected branch, tag or stash.
        DiscardRow ["x", "delete" in "Sidebar && !modal"] [hidden];
        /// Filter the branch list.
        FilterBranches ["/", "secondary-f" in "Sidebar && !modal"] [hidden];
    }

    view BlameView in blame context "BlameView && !modal && !TextInput" {
        /// Leave the blame view and go back to the diff.
        BlameShowDiff ["escape" in "BlameView && !modal", "d"] [hidden];
        /// Show the blamed file's commit history.
        BlameShowHistory "h" [hidden];
    }

    view FileHistoryView in history context "FileHistoryView && !modal && !TextInput" {
        /// Leave the file history and go back to the diff.
        HistoryShowDiff ["escape" in "FileHistoryView && !modal", "d"] [hidden];
        /// Blame the file whose history is shown.
        HistoryShowBlame "b" [hidden];
    }

    view InteractiveRebase in rebase context "InteractiveRebase && !TextInput" {
        /// Move the selected commit earlier in the rebase plan.
        RebaseMoveUp "secondary-up" in "InteractiveRebase" [hidden];
        /// Move the selected commit later in the rebase plan.
        RebaseMoveDown "secondary-down" in "InteractiveRebase" [hidden];
        /// Keep the selected commit as it is.
        RebasePick "p" [hidden];
        /// Reword the selected commit's message.
        RebaseReword "r" [hidden];
        /// Squash the selected commit into the previous one.
        RebaseSquash "s" [hidden];
        /// Squash the selected commit into the previous one, discarding its message.
        RebaseFixup "f" [hidden];
        /// Drop the selected commit.
        RebaseDrop "d" [hidden];
    }

    view ThemeEditor in theme context "ThemeEditor" {
        /// Focus the next field in the theme editor.
        ThemeEditorNextField "tab" [hidden];
        /// Focus the previous field in the theme editor.
        ThemeEditorPrevField "shift-tab" [hidden];
    }

    view CreatePrDialog in pr context "CreatePrDialog" {
        /// Open the pull request described in the dialog.
        SubmitPullRequest "shift-enter" [hidden];
    }
}

/// One element of the key-context tree — a `key_context(...)` call and where the
/// element carrying it sits.
///
/// gpui evaluates a binding's context predicate against every prefix of the path
/// from the window root down to the focused element and keeps the *deepest* match
/// ([`gpui::KeyBindingContextPredicate::depth_of`]); the deepest match wins. A
/// binding scoped to a panel therefore takes a keystroke away from a global
/// binding whenever that panel has focus.
///
/// `commands!` cannot see that: a `view` block says which context a binding is
/// scoped *to*, never where that context sits. So the shape is written out below
/// and [`super::shadow`] walks it to reconstruct the focus paths.
pub struct KeyContextNode {
    /// The element's key context, verbatim as passed to `key_context`. The first
    /// identifier names the element; any others are groups it joins, like `List`.
    pub context: &'static str,
    /// The enclosing element's [`Self::name`], or `None` for a window root.
    pub parent: Option<&'static str>,
    /// Whether the workspace root carries `modal` while this element is up, which
    /// is what makes `Workspace && !modal` bindings stand down. Mirrors
    /// `Workspace::any_overlay_active`, the gate that actually sets it.
    pub modal: bool,
    /// How to name the element in a message to the user, e.g. "the commit graph".
    pub label: &'static str,
}

impl KeyContextNode {
    /// The identifier naming this element — the first one in [`Self::context`].
    pub fn name(&self) -> &'static str {
        self.context
            .split_whitespace()
            .next()
            // Unreachable: `context_tree_is_well_formed` rejects an empty context.
            .expect("every node names its element")
    }

    /// Every identifier this element's key context sets.
    pub fn identifiers(&self) -> impl Iterator<Item = &'static str> {
        self.context.split_whitespace()
    }
}

/// The element tree the key contexts hang off, roots first.
///
/// Hand-written because the `key_context` calls it mirrors are spread across
/// three crates and only run at render time, so there is nothing to derive it
/// from. `every_registry_context_is_in_the_tree` fails when a `commands!` block
/// names a context that is missing here, so a new view cannot slip past
/// [`super::shadow`]'s analysis unnoticed.
pub const CONTEXT_TREE: &[KeyContextNode] = &[
    // Window roots. Each owns its own dispatch path — a binding scoped to one is
    // never reachable from the other, which is why `menu::Cancel` names both.
    KeyContextNode {
        context: "Workspace",
        parent: None,
        modal: false,
        label: "the main window",
    },
    KeyContextNode {
        context: "SettingsWindow",
        parent: None,
        modal: false,
        label: "the settings window",
    },
    // Panels. Always present, so a binding of theirs competes with a global one.
    KeyContextNode {
        context: "Sidebar List",
        parent: Some("Workspace"),
        modal: false,
        label: "the sidebar",
    },
    KeyContextNode {
        context: "GraphView",
        parent: Some("Workspace"),
        modal: false,
        label: "the commit graph",
    },
    KeyContextNode {
        context: "DetailPanel List",
        parent: Some("Workspace"),
        modal: false,
        label: "the commit detail panel",
    },
    KeyContextNode {
        context: "DiffViewer",
        parent: Some("Workspace"),
        modal: false,
        label: "the diff viewer",
    },
    KeyContextNode {
        context: "BlameView List",
        parent: Some("Workspace"),
        modal: false,
        label: "the blame view",
    },
    KeyContextNode {
        context: "FileHistoryView List",
        parent: Some("Workspace"),
        modal: false,
        label: "the file history",
    },
    KeyContextNode {
        context: "ReflogView List",
        parent: Some("Workspace"),
        modal: false,
        label: "the reflog",
    },
    KeyContextNode {
        context: "SubmoduleView List",
        parent: Some("Workspace"),
        modal: false,
        label: "the submodule list",
    },
    KeyContextNode {
        context: "BisectView List",
        parent: Some("Workspace"),
        modal: false,
        label: "the bisect log",
    },
    KeyContextNode {
        context: "IssuesPanel List",
        parent: Some("Workspace"),
        modal: false,
        label: "the issues panel",
    },
    KeyContextNode {
        context: "PrsPanel List",
        parent: Some("Workspace"),
        modal: false,
        label: "the pull requests panel",
    },
    // Overlays and dialogs. `modal: true` marks the ones
    // `Workspace::any_overlay_active` counts; the three that it does not are
    // spelled out below, so this table stays a description of what the app does
    // rather than of what it ought to do.
    KeyContextNode {
        context: "CommandPalette List",
        parent: Some("Workspace"),
        modal: true,
        label: "the command palette",
    },
    KeyContextNode {
        context: "SearchPanel List",
        parent: Some("Workspace"),
        modal: true,
        label: "the working-tree search",
    },
    KeyContextNode {
        context: "RepoOpener List",
        parent: Some("Workspace"),
        modal: true,
        label: "the repository picker",
    },
    KeyContextNode {
        context: "ShortcutsHelp",
        parent: Some("Workspace"),
        modal: true,
        label: "the shortcut reference",
    },
    KeyContextNode {
        context: "InteractiveRebase List",
        parent: Some("Workspace"),
        modal: true,
        label: "the interactive rebase editor",
    },
    KeyContextNode {
        context: "ThemeEditor",
        parent: Some("Workspace"),
        modal: true,
        label: "the theme editor",
    },
    KeyContextNode {
        context: "BranchDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the branch dialog",
    },
    KeyContextNode {
        context: "TagDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the tag dialog",
    },
    KeyContextNode {
        context: "WorktreeDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the worktree dialog",
    },
    KeyContextNode {
        context: "RenameDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the rename dialog",
    },
    KeyContextNode {
        context: "ConfirmDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the confirmation dialog",
    },
    KeyContextNode {
        context: "StashBranchDialog",
        parent: Some("Workspace"),
        modal: true,
        label: "the stash-branch dialog",
    },
    // These three are not in `any_overlay_active`, so global shortcuts stay live
    // behind them.
    KeyContextNode {
        context: "CreatePrDialog",
        parent: Some("Workspace"),
        modal: false,
        label: "the pull request dialog",
    },
    KeyContextNode {
        context: "RepoCloneDialog",
        parent: Some("Workspace"),
        modal: false,
        label: "the clone dialog",
    },
    KeyContextNode {
        context: "StashSaveDialog",
        parent: Some("Workspace"),
        modal: false,
        label: "the stash dialog",
    },
];

/// Identifiers that flag an element rather than name a place in the tree, so they
/// are absent from [`CONTEXT_TREE`] on purpose.
///
/// `modal` is added to the workspace root by whichever overlay is up — see
/// [`KeyContextNode::modal`]. `TextInput` is set by [`rgitui_ui::TextInput`],
/// which can appear under any of the nodes above.
pub const CONTEXT_MARKERS: &[&str] = &["modal", "TextInput"];

/// The node whose element sets `name`, if any.
pub fn context_node(name: &str) -> Option<&'static KeyContextNode> {
    CONTEXT_TREE.iter().find(|node| node.name() == name)
}

impl CommandId {
    /// Static metadata for this command.
    pub fn meta(self) -> &'static CommandMeta {
        ALL_COMMANDS
            .iter()
            .find(|meta| meta.id == self)
            // Unreachable: `ALL_COMMANDS` and `CommandId` are generated together.
            .expect("every CommandId has metadata")
    }

    /// This command's default bindings, or an empty slice when it has none.
    pub fn default_bindings(self) -> &'static [(&'static str, &'static str)] {
        self.meta().default_bindings
    }

    /// A one-line description of what this command does.
    pub fn description(self) -> &'static str {
        self.meta().description()
    }

    /// Whether this command is offered in the command palette.
    pub fn in_palette(self) -> bool {
        self.meta().in_palette
    }

    /// The command-palette availability predicate for this command.
    pub fn availability(self) -> fn(CommandContext) -> bool {
        self.meta().availability
    }
}

impl std::fmt::Display for CommandId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for CommandId {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        CommandId::ALL
            .iter()
            .copied()
            .find(|id| id.as_str() == value)
            .ok_or(())
    }
}

/// Looks up a command by its gpui action name (`namespace::Name`).
pub fn command_for_action(action_name: &str) -> Option<CommandId> {
    ALL_COMMANDS
        .iter()
        .find(|meta| meta.action_name == action_name)
        .map(|meta| meta.id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use gpui::KeyBindingContextPredicate;
    use std::collections::HashSet;

    /// The historical `CommandId::as_str()` values. These are persisted and
    /// matched by the command palette, so the generated snake_case conversion
    /// must reproduce them byte for byte.
    const LEGACY_IDS: &[(CommandId, &str)] = &[
        (CommandId::Fetch, "fetch"),
        (CommandId::Pull, "pull"),
        (CommandId::Push, "push"),
        (CommandId::PushAll, "push_all"),
        (CommandId::PullAll, "pull_all"),
        (CommandId::ForcePush, "force_push"),
        (CommandId::Commit, "commit"),
        (CommandId::StageAll, "stage_all"),
        (CommandId::UnstageAll, "unstage_all"),
        (CommandId::StashSave, "stash_save"),
        (CommandId::StashPop, "stash_pop"),
        (CommandId::StashApply, "stash_apply"),
        (CommandId::StashDrop, "stash_drop"),
        (CommandId::CreateBranch, "create_branch"),
        (CommandId::DeleteBranch, "delete_branch"),
        (CommandId::RenameBranch, "rename_branch"),
        (CommandId::MergeBranch, "merge_branch"),
        (CommandId::CreateTag, "create_tag"),
        (CommandId::CreateWorktree, "create_worktree"),
        (CommandId::CreatePr, "create_pr"),
        (CommandId::CherryPick, "cherry_pick"),
        (CommandId::RevertCommit, "revert_commit"),
        (CommandId::InteractiveRebase, "interactive_rebase"),
        (CommandId::DiscardAll, "discard_all"),
        (CommandId::CleanUntracked, "clean_untracked"),
        (CommandId::ResetHard, "reset_hard"),
        (CommandId::AbortOperation, "abort_operation"),
        (CommandId::ContinueMerge, "continue_merge"),
        (CommandId::ToggleDiffMode, "toggle_diff_mode"),
        (CommandId::Search, "search"),
        (CommandId::AiMessage, "ai_message"),
        (CommandId::Refresh, "refresh"),
        (CommandId::Settings, "settings"),
        (CommandId::OpenRepo, "open_repo"),
        (CommandId::WorkspaceHome, "workspace_home"),
        (CommandId::RestoreLastWorkspace, "restore_last_workspace"),
        (CommandId::Shortcuts, "shortcuts"),
        (CommandId::SwitchBranch, "switch_branch"),
        (CommandId::Blame, "blame"),
        (CommandId::Undo, "undo"),
        (CommandId::FileHistory, "file_history"),
        (CommandId::Reflog, "reflog"),
        (CommandId::Submodules, "submodules"),
        (CommandId::Bisect, "bisect"),
        (CommandId::BisectStart, "bisect_start"),
        (CommandId::BisectGood, "bisect_good"),
        (CommandId::BisectBad, "bisect_bad"),
        (CommandId::BisectReset, "bisect_reset"),
        (CommandId::BisectSkip, "bisect_skip"),
        (CommandId::GlobalSearch, "global_search"),
        (CommandId::ToggleIssues, "toggle_issues"),
        (CommandId::TogglePullRequests, "toggle_pull_requests"),
        (CommandId::ToggleBranchHealth, "toggle_branch_health"),
        (CommandId::ToggleStashes, "toggle_stashes"),
        (CommandId::StashBranch, "stash_branch"),
        (CommandId::OpenThemeEditor, "open_theme_editor"),
    ];

    #[test]
    fn command_id_strings_are_stable() {
        for (id, expected) in LEGACY_IDS {
            assert_eq!(id.as_str(), *expected, "as_str drifted for {id:?}");
        }
    }

    #[test]
    fn command_ids_round_trip_through_strings() {
        for id in CommandId::ALL {
            assert_eq!(
                CommandId::try_from(id.as_str()),
                Ok(*id),
                "{id:?} did not round-trip"
            );
        }
        assert_eq!(CommandId::try_from("not_a_command"), Err(()));
    }

    #[test]
    fn command_ids_are_unique() {
        let ids: HashSet<&str> = CommandId::ALL.iter().map(|id| id.as_str()).collect();
        assert_eq!(ids.len(), CommandId::ALL.len());
    }

    #[test]
    fn registry_covers_every_command() {
        assert_eq!(ALL_COMMANDS.len(), CommandId::ALL.len());
        for (meta, id) in ALL_COMMANDS.iter().zip(CommandId::ALL) {
            assert_eq!(meta.id, *id);
        }
    }

    #[test]
    fn action_names_are_namespaced_and_unique() {
        let mut names = HashSet::new();
        for meta in ALL_COMMANDS {
            assert!(
                meta.action_name
                    .starts_with(&format!("{}::", meta.namespace)),
                "{} is not namespaced",
                meta.action_name
            );
            let bare = meta
                .action_name
                .trim_start_matches(&format!("{}::", meta.namespace));
            assert!(
                !bare.contains("::"),
                "gpui panics on action names containing `::`: {}",
                meta.action_name
            );
            assert!(
                names.insert(meta.action_name),
                "duplicate {}",
                meta.action_name
            );
            assert_eq!(command_for_action(meta.action_name), Some(meta.id));
        }
    }

    /// Guards the runtime path: `keymap.json` resolves actions by name through
    /// `App::build_action`, which only knows the actions gpui collected from the
    /// `inventory` registry at link time. If the generated structs were ever
    /// dropped by the linker every binding would silently fail to load.
    #[test]
    fn every_action_is_registered_with_gpui() {
        let registered: HashSet<&str> = gpui::generate_list_of_all_registered_actions()
            .map(|action| action.name)
            .collect();
        for meta in ALL_COMMANDS {
            assert!(
                registered.contains(meta.action_name),
                "{} is not registered with gpui, so keymap.json could not name it",
                meta.action_name
            );
        }
    }

    /// The doc comment on each command becomes the action's `documentation()`,
    /// which is what a future keybinding editor would show.
    #[test]
    fn action_documentation_comes_from_the_doc_comment() {
        let documented: Vec<(&str, Option<&str>)> = gpui::generate_list_of_all_registered_actions()
            .map(|action| (action.name, action.documentation))
            .collect();
        for meta in ALL_COMMANDS {
            let (_, documentation) = documented
                .iter()
                .find(|(name, _)| *name == meta.action_name)
                .expect("every action is registered");
            assert_eq!(
                *documentation,
                Some(meta.description()),
                "{} documentation drifted from its doc comment",
                meta.action_name
            );
        }
    }

    #[test]
    fn every_command_is_documented() {
        for meta in ALL_COMMANDS {
            assert!(
                !meta.description().is_empty(),
                "{} has no doc comment",
                meta.action_name
            );
        }
    }

    /// Every `(keystrokes, context, action)` triple the registry declares.
    fn default_bindings() -> Vec<(&'static str, &'static str, &'static str)> {
        ALL_COMMANDS
            .iter()
            .flat_map(|meta| {
                meta.default_bindings
                    .iter()
                    .map(move |(keystrokes, context)| (*keystrokes, *context, meta.action_name))
            })
            .collect()
    }

    /// The actions a keystroke is bound to, paired with the context of each.
    fn bindings_for(keystrokes: &str) -> Vec<(&'static str, &'static str)> {
        default_bindings()
            .into_iter()
            .filter(|(keys, _, _)| *keys == keystrokes)
            .map(|(_, context, action)| (action, context))
            .collect()
    }

    /// Whether a keystroke is one a user could be typing into a text field: no
    /// modifier beyond shift, and a single printable key.
    fn is_typeable(keystrokes: &str) -> bool {
        let mut parts = keystrokes.split_whitespace();
        let (Some(single), None) = (parts.next(), parts.next()) else {
            // A chord always starts with a modifier in this registry.
            return false;
        };
        let Ok(keystroke) = gpui::Keystroke::parse(single) else {
            return false;
        };
        let modifiers = keystroke.modifiers;
        if modifiers.control || modifiers.alt || modifiers.platform || modifiers.function {
            return false;
        }
        keystroke.key.chars().count() == 1 || keystroke.key == "space"
    }

    /// gpui dispatches bindings deepest-context first, so one letter can mean
    /// different things in different panels. Each of these is bound several
    /// times over, and every binding must name a distinct action in a distinct
    /// context — otherwise one of them is dead.
    #[test]
    fn ambiguous_letters_resolve_to_one_action_per_context() {
        for keystrokes in ["d", "s", "p", "b", "h", "j", "k", "g", "y", "/", "[", "]"] {
            let bindings = bindings_for(keystrokes);
            assert!(
                !bindings.is_empty(),
                "`{keystrokes}` is documented as context-sensitive but is not bound at all"
            );

            let actions: HashSet<&str> = bindings.iter().map(|(action, _)| *action).collect();
            assert_eq!(
                actions.len(),
                bindings.len(),
                "`{keystrokes}` binds the same action twice: {bindings:?}"
            );

            let contexts: HashSet<&str> = bindings.iter().map(|(_, context)| *context).collect();
            assert_eq!(
                contexts.len(),
                bindings.len(),
                "`{keystrokes}` binds two actions in the same context, so one never fires: \
                 {bindings:?}"
            );
        }
    }

    /// The four letters the migration called out by name, pinned to the view that
    /// owns each so a future block cannot quietly steal one.
    #[test]
    fn the_overloaded_letters_are_owned_by_the_expected_views() {
        let expected: &[(&str, &[&str])] = &[
            (
                "d",
                &[
                    "diff::ToggleDiffDisplayMode",
                    "blame::BlameShowDiff",
                    "history::HistoryShowDiff",
                    "rebase::RebaseDrop",
                ],
            ),
            (
                "s",
                &[
                    "graph::SquashSelected",
                    "diff::StageSelection",
                    "sidebar::ToggleStageRow",
                    "rebase::RebaseSquash",
                ],
            ),
            ("p", &["diff::TogglePartialSelection", "rebase::RebasePick"]),
            ("b", &["history::HistoryShowBlame"]),
            ("h", &["blame::BlameShowHistory"]),
        ];

        for (keystrokes, actions) in expected {
            let bound: HashSet<&str> = bindings_for(keystrokes)
                .into_iter()
                .map(|(action, _)| action)
                .collect();
            let want: HashSet<&str> = actions.iter().copied().collect();
            assert_eq!(bound, want, "the owners of `{keystrokes}` changed");
        }
    }

    /// gpui dispatches keymap bindings *before* `on_key_down`, so any binding a
    /// user could type must stand down while a text field is focused. `!TextInput`
    /// is false whenever a text field is anywhere on the focus path, which is
    /// exactly the guarantee needed.
    #[test]
    fn bare_character_bindings_stand_down_for_text_input() {
        for (keystrokes, context, action) in default_bindings() {
            if !is_typeable(keystrokes) {
                continue;
            }
            assert!(
                context.contains("!TextInput"),
                "`{keystrokes}` is bound to {action} in context `{context}`, which would swallow \
                 the character while a text field has focus; add `&& !TextInput`"
            );
        }
    }

    /// The shared dismissal must be reachable from both windows, since each owns
    /// its own Esc handling and Esc never crosses windows.
    #[test]
    fn cancel_and_confirm_are_bound_across_both_window_roots() {
        for (id, keystrokes) in [(CommandId::Cancel, "escape"), (CommandId::Confirm, "enter")] {
            let context = id
                .default_bindings()
                .iter()
                .find(|(keys, _)| *keys == keystrokes)
                .map(|(_, context)| *context)
                .unwrap_or_else(|| panic!("{id} is not bound to `{keystrokes}`"));
            assert!(context.contains("Workspace"), "{id}: `{context}`");
            assert!(context.contains("SettingsWindow"), "{id}: `{context}`");
        }
    }

    /// The per-keystroke `in "..."` override: `down` stays live inside a text
    /// field while the vim-style `j` for the same command stands down.
    #[test]
    fn one_command_can_bind_keystrokes_in_different_contexts() {
        assert_eq!(
            CommandId::SelectNext.default_bindings(),
            &[("down", "List"), ("j", "List && !TextInput")]
        );
        assert_eq!(
            CommandId::SelectLast.default_bindings(),
            &[("end", "List"), ("shift-g", "List && !TextInput")]
        );
    }

    /// A view block's `context` is the default for its commands, and a
    /// per-command `in "..."` overrides it.
    #[test]
    fn a_view_context_is_inherited_unless_overridden() {
        assert_eq!(
            CommandId::BlameShowDiff.default_bindings(),
            &[
                ("escape", "BlameView && !modal"),
                ("d", "BlameView && !modal && !TextInput")
            ]
        );
        assert_eq!(
            CommandId::BlameShowHistory.default_bindings(),
            &[("h", "BlameView && !modal && !TextInput")]
        );
    }

    /// Every identifier a context predicate mentions, negated ones included —
    /// `!TextInput` still has to be accounted for by the tree or the markers.
    fn predicate_identifiers(predicate: &gpui::KeyBindingContextPredicate, out: &mut Vec<String>) {
        use gpui::KeyBindingContextPredicate as P;
        match predicate {
            P::Identifier(name) => out.push(name.to_string()),
            P::Equal(key, _) | P::NotEqual(key, _) => out.push(key.to_string()),
            P::Not(inner) => predicate_identifiers(inner, out),
            P::Descendant(left, right) | P::And(left, right) | P::Or(left, right) => {
                predicate_identifiers(left, out);
                predicate_identifiers(right, out);
            }
        }
    }

    #[test]
    fn context_tree_is_well_formed() {
        let mut names = HashSet::new();
        for node in CONTEXT_TREE {
            assert!(
                !node.context.trim().is_empty(),
                "a node has no key context at all"
            );
            assert!(
                !node.label.trim().is_empty(),
                "{} has no user-facing label",
                node.name()
            );
            assert!(names.insert(node.name()), "{} appears twice", node.name());
        }

        for node in CONTEXT_TREE {
            let Some(parent) = node.parent else {
                continue;
            };
            assert!(
                names.contains(&parent),
                "{}'s parent `{parent}` is not in the tree",
                node.name()
            );
            // Walking up must terminate at a root rather than loop.
            let mut current = node;
            let mut hops = 0;
            while let Some(parent) = current.parent {
                current = context_node(parent).expect("the parent is in the tree");
                hops += 1;
                assert!(
                    hops <= CONTEXT_TREE.len(),
                    "{} sits in a parent cycle",
                    node.name()
                );
            }
        }

        let roots: Vec<&str> = CONTEXT_TREE
            .iter()
            .filter(|node| node.parent.is_none())
            .map(KeyContextNode::name)
            .collect();
        assert_eq!(
            roots,
            ["Workspace", "SettingsWindow"],
            "each window root owns its own dispatch path; adding one is a decision, \
             not an accident"
        );
    }

    /// The guard that keeps [`CONTEXT_TREE`] honest: a new `commands!` block
    /// naming a context nobody placed in the tree would escape the shadowing
    /// analysis silently, so it fails the build instead.
    #[test]
    fn every_registry_context_is_in_the_tree() {
        let mut known: HashSet<&str> = CONTEXT_MARKERS.iter().copied().collect();
        known.extend(CONTEXT_TREE.iter().flat_map(KeyContextNode::identifiers));

        for (keystrokes, context, action) in default_bindings() {
            let predicate = KeyBindingContextPredicate::parse(context)
                .unwrap_or_else(|error| panic!("`{context}` does not parse: {error}"));
            let mut identifiers = Vec::new();
            predicate_identifiers(&predicate, &mut identifiers);
            for identifier in identifiers {
                assert!(
                    known.contains(identifier.as_str()),
                    "`{identifier}` (from the `{context}` binding of `{keystrokes}` to {action}) \
                     is in no CONTEXT_TREE node and is not a marker, so shadowing against it \
                     cannot be detected. Add the element to CONTEXT_TREE in this file."
                );
            }
        }
    }

    #[test]
    fn hidden_commands_are_the_ones_absent_from_the_palette() {
        let palette: HashSet<CommandId> = crate::command_palette::palette_commands()
            .iter()
            .map(|command| command.id)
            .collect();
        for meta in ALL_COMMANDS {
            assert_eq!(
                palette.contains(&meta.id),
                meta.in_palette,
                "{} palette membership disagrees with the `[hidden]` marker",
                meta.action_name
            );
        }
    }

    #[test]
    fn palette_predicates_match_the_registry() {
        for command in crate::command_palette::palette_commands() {
            let expected = command.id.availability();
            assert!(
                std::ptr::fn_addr_eq(command.predicate(), expected),
                "{} availability predicate disagrees with the registry",
                command.id
            );
        }
    }
}
