//! The command registry: one `commands!` declaration that defines every
//! rgitui command, its gpui action and its default key binding.
//!
//! # Key contexts
//!
//! `Workspace` is set on the workspace root element. The root adds `modal`
//! whenever an overlay or dialog is open, so `Workspace && !modal` is the
//! scope for shortcuts that must not fire while a modal is up — it replaces
//! the hand-rolled `any_overlay_active` gate for the commands listed here.
//! `TextInput` is set by [`rgitui_ui::TextInput`], so `!TextInput` keeps
//! unmodified single-key shortcuts from stealing typed characters.

// The `if <predicate>` clause of `commands!` resolves these by name at the
// invocation site; `always_show` is the default and is referenced through
// `$crate`, so it is not imported here.
use crate::command_palette::{
    has_changes, has_github_token, has_remotes, has_staged, has_stashes, in_progress_operation,
    is_bisecting, worktree_clean, CommandContext,
};

/// Static description of a single command.
///
/// Generated by `commands!`; see [`ALL_COMMANDS`].
pub struct CommandMeta {
    /// The command this metadata describes.
    pub id: CommandId,
    /// The view whose `commands!` block declared it. Groups the generated docs.
    pub view: &'static str,
    /// The gpui action namespace.
    pub namespace: &'static str,
    /// The full gpui action name, as written in `keymap.json`.
    pub action_name: &'static str,
    /// Default keystrokes. Empty when the command has no default binding.
    pub default_keystrokes: &'static [&'static str],
    /// Key context predicate the default bindings are scoped to.
    pub context: &'static str,
    /// Doc comment from the declaration. Leading whitespace is not trimmed.
    pub description: &'static str,
    /// Whether the command is offered in the command palette.
    pub in_palette: bool,
    /// Command-palette availability predicate.
    pub availability: fn(CommandContext) -> bool,
}

impl CommandMeta {
    /// The description with doc-comment padding removed.
    pub fn description(&self) -> &'static str {
        self.description.trim()
    }
}

commands! {
    view Workspace in rgitui context "Workspace && !modal" {
        /// Download objects and refs from the tracked remote.
        Fetch "secondary-shift-r" if has_remotes;
        /// Fetch from and integrate with the tracked remote branch.
        Pull unbound if has_remotes;
        /// Update the remote ref along with associated objects.
        Push unbound if has_remotes;
        /// Push every open repository.
        PushAll unbound if has_remotes;
        /// Pull every open repository.
        PullAll unbound if has_remotes;
        /// Overwrite the remote branch with the local one.
        ForcePush unbound if has_remotes;
        /// Commit the staged changes using the message in the commit panel.
        Commit "secondary-enter" if has_staged;
        /// Stage every change in the working tree.
        StageAll "secondary-s" if has_changes;
        /// Unstage everything currently staged.
        UnstageAll ["secondary-shift-s", "secondary-u"] if has_changes;
        /// Stash the working tree and index.
        StashSave "secondary-z" if has_changes;
        /// Apply the latest stash entry and drop it.
        StashPop "secondary-shift-z" if has_stashes;
        /// Apply the latest stash entry and keep it.
        StashApply unbound if has_stashes;
        /// Delete a stash entry.
        StashDrop unbound if has_stashes;
        /// Create a new branch.
        CreateBranch "secondary-b";
        /// Delete a branch.
        DeleteBranch unbound;
        /// Rename a branch.
        RenameBranch unbound;
        /// Merge another branch into the current one.
        MergeBranch unbound if worktree_clean;
        /// Create a tag.
        CreateTag unbound;
        /// Create a linked worktree.
        CreateWorktree unbound;
        /// Open a pull request for the current branch.
        CreatePr unbound if has_github_token;
        /// Cherry-pick a commit onto the current branch.
        CherryPick unbound if worktree_clean;
        /// Revert a commit.
        RevertCommit unbound if worktree_clean;
        /// Start an interactive rebase.
        InteractiveRebase unbound if worktree_clean;
        /// Discard every uncommitted change.
        DiscardAll unbound if has_changes;
        /// Delete untracked files.
        CleanUntracked unbound;
        /// Reset the working tree and index to HEAD.
        ResetHard unbound if has_changes;
        /// Abort the merge, rebase, cherry-pick or revert in progress.
        AbortOperation unbound if in_progress_operation;
        /// Continue the merge, rebase, cherry-pick or revert in progress.
        ContinueMerge unbound if in_progress_operation;
        /// Switch the diff viewer between unified and side-by-side.
        ToggleDiffMode unbound;
        /// Search the commit graph.
        Search unbound;
        /// Generate a commit message with the configured AI provider.
        AiMessage "secondary-g" if has_staged;
        /// Reload the repository state from disk.
        Refresh "f5";
        /// Open the settings window.
        Settings "secondary-," in "Workspace";
        /// Open the repository picker.
        OpenRepo "secondary-o" in "Workspace";
        /// Close every tab and return to the workspace home screen.
        WorkspaceHome "secondary-h";
        /// Reopen the most recently saved workspace.
        RestoreLastWorkspace unbound;
        /// Show the keyboard shortcut reference.
        Shortcuts "?" in "Workspace && !TextInput";
        /// Focus the sidebar to switch branches.
        SwitchBranch "secondary-shift-b";
        /// Blame the selected file.
        Blame unbound;
        /// Undo the last git operation.
        Undo unbound;
        /// Show the commit history of the selected file.
        FileHistory unbound;
        /// Show the reflog.
        Reflog unbound;
        /// Show the submodule list.
        Submodules unbound;
        /// Show the bisect log.
        Bisect unbound if is_bisecting;
        /// Start a bisect session.
        BisectStart unbound if worktree_clean;
        /// Mark the current bisect commit as good.
        BisectGood unbound if is_bisecting;
        /// Mark the current bisect commit as bad.
        BisectBad unbound if is_bisecting;
        /// End the bisect session and restore HEAD.
        BisectReset unbound if is_bisecting;
        /// Skip the current bisect commit.
        BisectSkip unbound if is_bisecting;
        /// Search the contents of the working tree.
        GlobalSearch unbound;
        /// Toggle the issues panel.
        ToggleIssues "alt-5";
        /// Toggle the pull requests panel.
        TogglePullRequests "alt-6";
        /// Toggle the branch health panel.
        ToggleBranchHealth "alt-7";
        /// Toggle the stashes panel.
        ToggleStashes "alt-8";
        /// Create a branch from a stash entry.
        StashBranch unbound if has_stashes;
        /// Open the theme editor.
        OpenThemeEditor ["secondary-shift-t", "alt-9"] in "Workspace";
        /// Toggle the command palette.
        CommandPalette "secondary-shift-p" in "Workspace" [hidden];
        /// Activate the next repository tab.
        NextTab "secondary-tab" [hidden];
        /// Activate the previous repository tab.
        PrevTab "secondary-shift-tab" [hidden];
        /// Close the active repository tab.
        CloseTab "secondary-w" [hidden];
    }
}

impl CommandId {
    /// Static metadata for this command.
    pub fn meta(self) -> &'static CommandMeta {
        ALL_COMMANDS
            .iter()
            .find(|meta| meta.id == self)
            // Unreachable: `ALL_COMMANDS` and `CommandId` are generated together.
            .expect("every CommandId has metadata")
    }

    /// The key context the default bindings for this command are scoped to.
    pub fn context(self) -> &'static str {
        self.meta().context
    }

    /// This command's default keystrokes, or an empty slice when it has none.
    pub fn default_keystrokes(self) -> &'static [&'static str] {
        self.meta().default_keystrokes
    }

    /// A one-line description of what this command does.
    pub fn description(self) -> &'static str {
        self.meta().description()
    }

    /// Whether this command is offered in the command palette.
    pub fn in_palette(self) -> bool {
        self.meta().in_palette
    }

    /// The command-palette availability predicate for this command.
    pub fn availability(self) -> fn(CommandContext) -> bool {
        self.meta().availability
    }
}

impl std::fmt::Display for CommandId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for CommandId {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        CommandId::ALL
            .iter()
            .copied()
            .find(|id| id.as_str() == value)
            .ok_or(())
    }
}

/// Looks up a command by its gpui action name (`namespace::Name`).
pub fn command_for_action(action_name: &str) -> Option<CommandId> {
    ALL_COMMANDS
        .iter()
        .find(|meta| meta.action_name == action_name)
        .map(|meta| meta.id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// The historical `CommandId::as_str()` values. These are persisted and
    /// matched by the command palette, so the generated snake_case conversion
    /// must reproduce them byte for byte.
    const LEGACY_IDS: &[(CommandId, &str)] = &[
        (CommandId::Fetch, "fetch"),
        (CommandId::Pull, "pull"),
        (CommandId::Push, "push"),
        (CommandId::PushAll, "push_all"),
        (CommandId::PullAll, "pull_all"),
        (CommandId::ForcePush, "force_push"),
        (CommandId::Commit, "commit"),
        (CommandId::StageAll, "stage_all"),
        (CommandId::UnstageAll, "unstage_all"),
        (CommandId::StashSave, "stash_save"),
        (CommandId::StashPop, "stash_pop"),
        (CommandId::StashApply, "stash_apply"),
        (CommandId::StashDrop, "stash_drop"),
        (CommandId::CreateBranch, "create_branch"),
        (CommandId::DeleteBranch, "delete_branch"),
        (CommandId::RenameBranch, "rename_branch"),
        (CommandId::MergeBranch, "merge_branch"),
        (CommandId::CreateTag, "create_tag"),
        (CommandId::CreateWorktree, "create_worktree"),
        (CommandId::CreatePr, "create_pr"),
        (CommandId::CherryPick, "cherry_pick"),
        (CommandId::RevertCommit, "revert_commit"),
        (CommandId::InteractiveRebase, "interactive_rebase"),
        (CommandId::DiscardAll, "discard_all"),
        (CommandId::CleanUntracked, "clean_untracked"),
        (CommandId::ResetHard, "reset_hard"),
        (CommandId::AbortOperation, "abort_operation"),
        (CommandId::ContinueMerge, "continue_merge"),
        (CommandId::ToggleDiffMode, "toggle_diff_mode"),
        (CommandId::Search, "search"),
        (CommandId::AiMessage, "ai_message"),
        (CommandId::Refresh, "refresh"),
        (CommandId::Settings, "settings"),
        (CommandId::OpenRepo, "open_repo"),
        (CommandId::WorkspaceHome, "workspace_home"),
        (CommandId::RestoreLastWorkspace, "restore_last_workspace"),
        (CommandId::Shortcuts, "shortcuts"),
        (CommandId::SwitchBranch, "switch_branch"),
        (CommandId::Blame, "blame"),
        (CommandId::Undo, "undo"),
        (CommandId::FileHistory, "file_history"),
        (CommandId::Reflog, "reflog"),
        (CommandId::Submodules, "submodules"),
        (CommandId::Bisect, "bisect"),
        (CommandId::BisectStart, "bisect_start"),
        (CommandId::BisectGood, "bisect_good"),
        (CommandId::BisectBad, "bisect_bad"),
        (CommandId::BisectReset, "bisect_reset"),
        (CommandId::BisectSkip, "bisect_skip"),
        (CommandId::GlobalSearch, "global_search"),
        (CommandId::ToggleIssues, "toggle_issues"),
        (CommandId::TogglePullRequests, "toggle_pull_requests"),
        (CommandId::ToggleBranchHealth, "toggle_branch_health"),
        (CommandId::ToggleStashes, "toggle_stashes"),
        (CommandId::StashBranch, "stash_branch"),
        (CommandId::OpenThemeEditor, "open_theme_editor"),
    ];

    #[test]
    fn command_id_strings_are_stable() {
        for (id, expected) in LEGACY_IDS {
            assert_eq!(id.as_str(), *expected, "as_str drifted for {id:?}");
        }
    }

    #[test]
    fn command_ids_round_trip_through_strings() {
        for id in CommandId::ALL {
            assert_eq!(
                CommandId::try_from(id.as_str()),
                Ok(*id),
                "{id:?} did not round-trip"
            );
        }
        assert_eq!(CommandId::try_from("not_a_command"), Err(()));
    }

    #[test]
    fn command_ids_are_unique() {
        let ids: HashSet<&str> = CommandId::ALL.iter().map(|id| id.as_str()).collect();
        assert_eq!(ids.len(), CommandId::ALL.len());
    }

    #[test]
    fn registry_covers_every_command() {
        assert_eq!(ALL_COMMANDS.len(), CommandId::ALL.len());
        for (meta, id) in ALL_COMMANDS.iter().zip(CommandId::ALL) {
            assert_eq!(meta.id, *id);
        }
    }

    #[test]
    fn action_names_are_namespaced_and_unique() {
        let mut names = HashSet::new();
        for meta in ALL_COMMANDS {
            assert!(
                meta.action_name
                    .starts_with(&format!("{}::", meta.namespace)),
                "{} is not namespaced",
                meta.action_name
            );
            let bare = meta
                .action_name
                .trim_start_matches(&format!("{}::", meta.namespace));
            assert!(
                !bare.contains("::"),
                "gpui panics on action names containing `::`: {}",
                meta.action_name
            );
            assert!(
                names.insert(meta.action_name),
                "duplicate {}",
                meta.action_name
            );
            assert_eq!(command_for_action(meta.action_name), Some(meta.id));
        }
    }

    /// Guards the runtime path: `keymap.json` resolves actions by name through
    /// `App::build_action`, which only knows the actions gpui collected from the
    /// `inventory` registry at link time. If the generated structs were ever
    /// dropped by the linker every binding would silently fail to load.
    #[test]
    fn every_action_is_registered_with_gpui() {
        let registered: HashSet<&str> = gpui::generate_list_of_all_registered_actions()
            .map(|action| action.name)
            .collect();
        for meta in ALL_COMMANDS {
            assert!(
                registered.contains(meta.action_name),
                "{} is not registered with gpui, so keymap.json could not name it",
                meta.action_name
            );
        }
    }

    /// The doc comment on each command becomes the action's `documentation()`,
    /// which is what a future keybinding editor would show.
    #[test]
    fn action_documentation_comes_from_the_doc_comment() {
        let documented: Vec<(&str, Option<&str>)> = gpui::generate_list_of_all_registered_actions()
            .map(|action| (action.name, action.documentation))
            .collect();
        for meta in ALL_COMMANDS {
            let (_, documentation) = documented
                .iter()
                .find(|(name, _)| *name == meta.action_name)
                .expect("every action is registered");
            assert_eq!(
                *documentation,
                Some(meta.description()),
                "{} documentation drifted from its doc comment",
                meta.action_name
            );
        }
    }

    #[test]
    fn every_command_is_documented() {
        for meta in ALL_COMMANDS {
            assert!(
                !meta.description().is_empty(),
                "{} has no doc comment",
                meta.action_name
            );
        }
    }

    #[test]
    fn hidden_commands_are_the_ones_absent_from_the_palette() {
        let palette: HashSet<CommandId> = crate::command_palette::palette_commands()
            .iter()
            .map(|command| command.id)
            .collect();
        for meta in ALL_COMMANDS {
            assert_eq!(
                palette.contains(&meta.id),
                meta.in_palette,
                "{} palette membership disagrees with the `[hidden]` marker",
                meta.action_name
            );
        }
    }

    #[test]
    fn palette_predicates_match_the_registry() {
        for command in crate::command_palette::palette_commands() {
            let expected = command.id.availability();
            assert!(
                std::ptr::fn_addr_eq(command.predicate(), expected),
                "{} availability predicate disagrees with the registry",
                command.id
            );
        }
    }
}
